services:
  agent:
    build: ./
    container_name: caesar-agent
    environment:
      - SERVER_HOST=${SERVER_HOST:-host.docker.internal}
      - WEBSOCKET_PORT=${WEBSOCKET_PORT:-8765}
      - SCAN_INTERVAL=${SCAN_INTERVAL:-300}
      - IP_INTERFACE=${IP_INTERFACE:-}
    extra_hosts:
      - "host.docker.internal:host-gateway"
